project:
  type: website

website:
  title: ""
  search: 
    location: navbar
    type: textbox
  navbar:
    background: primary
    pinned: true
    left: 
      - icon: projects
        href: projects
    right:
      #- icon: envelope
      #  aria-label: email
      #  href: "mailto:"
      - icon: github
        href: https://github.com/annariha
format:
  html:
    theme: flatly
    css: styles.css
